### ISSUE TITLE
start failed in docker

### ISSUE THREAD

**Issue by qqletter** [sqlpad/sqlpad#1220]
I use sqlpad with docker image(sqlpad/sqlpad:latest)

After I install the newest version, the docker container failed to start.

docker logs as below:

Please migrate your code to use AWS SDK for JavaScript (v3).
For more information, check the migration guide at https://a.co/7PzMCcy
(Use `node --trace-warnings ...` to show where the warning was created)
node:internal/modules/cjs/loader:1282
  return process.dlopen(module, path.toNamespacedPath(filename));
                 ^

Error: libodbc.so.2: cannot open shared object file: No such file or directory
    at Object.Module._extensions..node (node:internal/modules/cjs/loader:1282:18)
    at Module.load (node:internal/modules/cjs/loader:1076:32)
    at Function.Module._load (node:internal/modules/cjs/loader:911:12)
    at Module.require (node:internal/modules/cjs/loader:1100:19)
    at require (node:internal/modules/cjs/helpers:119:18)
    at Object.<anonymous> (/usr/app/node_modules/odbc/lib/odbc.js:6:20)
    at Module._compile (node:internal/modules/cjs/loader:1198:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1252:10)
    at Module.load (node:internal/modules/cjs/loader:1076:32)
    at Function.Module._load (node:internal/modules/cjs/loader:911:12)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/translators:169:29)
    at ModuleJob.run (node:internal/modules/esm/module_job:193:25)
    at async Promise.all (index 0)
    at async ESMLoader.import (node:internal/modules/esm/loader:530:24)
    at async initDrivers (file:///usr/app/drivers/index.js:46:24)
    at async startServer (file:///usr/app/server.js:172:3) {
  code: 'ERR_DLOPEN_FAILED'
}

**Comment by rickbergfalk** [comment]
Hi @qqletter

I'm unable to reproduce this. Can you try removing the image Can I get any additional info on how you are running the docker image?

On Macos 14.3 with apple chip on latest docker, the following works for me run from command line

```sh
docker run -p 3000:3000 -e "SQLPAD_ADMIN=admin@sqlpad.com" -e "SQLPAD_ADMIN_PASSWORD=admin" sqlpad/sqlpad:latest
```

**Comment by simonst** [comment]
I have actually the same Issue when running the Docker Image 7.3.0 on Kubernetes connected to an external backend MariaDB.
`sqlpad-cccbf4c9f-jlv8t sqlpad {"level":30,"time":"2024-01-29T07:37:47.816Z","pid":1,"hostname":"sqlpad-cccbf4c9f-jlv8t","name":"sqlpad-app","msg":"Running migrations"}
sqlpad-cccbf4c9f-jlv8t sqlpad {"level":30,"time":"2024-01-29T07:37:47.821Z","pid":1,"hostname":"sqlpad-cccbf4c9f-jlv8t","name":"sqlpad-app","msg":"Migration finished"}
sqlpad-cccbf4c9f-jlv8t sqlpad {"level":30,"time":"2024-01-29T07:37:47.821Z","pid":1,"hostname":"sqlpad-cccbf4c9f-jlv8t","name":"sqlpad-app","msg":"Loading odbc"}
sqlpad-cccbf4c9f-jlv8t sqlpad {"level":30,"time":"2024-01-29T07:37:47.828Z","pid":1,"hostname":"sqlpad-cccbf4c9f-jlv8t","name":"sqlpad-app","msg":"ODBC driver not available"}
sqlpad-cccbf4c9f-jlv8t sqlpad node:internal/modules/cjs/loader:1282
sqlpad-cccbf4c9f-jlv8t sqlpad   return process.dlopen(module, path.toNamespacedPath(filename));
sqlpad-cccbf4c9f-jlv8t sqlpad                  ^
sqlpad-cccbf4c9f-jlv8t sqlpad
sqlpad-cccbf4c9f-jlv8t sqlpad Error: libodbc.so.2: cannot open shared object file: No such file or directory
sqlpad-cccbf4c9f-jlv8t sqlpad     at Object.Module._extensions..node (node:internal/modules/cjs/loader:1282:18)
sqlpad-cccbf4c9f-jlv8t sqlpad     at Module.load (node:internal/modules/cjs/loader:1076:32)
sqlpad-cccbf4c9f-jlv8t sqlpad     at Function.Module._load (node:internal/modules/cjs/loader:911:12)
sqlpad-cccbf4c9f-jlv8t sqlpad     at Module.require (node:internal/modules/cjs/loader:1100:19)
sqlpad-cccbf4c9f-jlv8t sqlpad     at require (node:internal/modules/cjs/helpers:119:18)
sqlpad-cccbf4c9f-jlv8t sqlpad     at Object.<anonymous> (/usr/app/node_modules/odbc/lib/odbc.js:6:20)
sqlpad-cccbf4c9f-jlv8t sqlpad     at Module._compile (node:internal/modules/cjs/loader:1198:14)
sqlpad-cccbf4c9f-jlv8t sqlpad     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1252:10)
sqlpad-cccbf4c9f-jlv8t sqlpad     at Module.load (node:internal/modules/cjs/loader:1076:32)
sqlpad-cccbf4c9f-jlv8t sqlpad     at Function.Module._load (node:internal/modules/cjs/loader:911:12)
sqlpad-cccbf4c9f-jlv8t sqlpad     at ModuleWrap.<anonymous> (node:internal/modules/esm/translators:169:29)
sqlpad-cccbf4c9f-jlv8t sqlpad     at ModuleJob.run (node:internal/modules/esm/module_job:193:25)
sqlpad-cccbf4c9f-jlv8t sqlpad     at async Promise.all (index 0)
sqlpad-cccbf4c9f-jlv8t sqlpad     at async ESMLoader.import (node:internal/modules/esm/loader:530:24)
sqlpad-cccbf4c9f-jlv8t sqlpad     at async initDrivers (file:///usr/app/drivers/index.js:46:24)
sqlpad-cccbf4c9f-jlv8t sqlpad     at async startServer (file:///usr/app/server.js:172:3) {
sqlpad-cccbf4c9f-jlv8t sqlpad   code: 'ERR_DLOPEN_FAILED'
sqlpad-cccbf4c9f-jlv8t sqlpad }`

When running 7.2.0 with exactly the same deployment config, there is no issue.

**Comment by qqletter** [comment]
> Hi @qqletter
> 
> I'm unable to reproduce this. Can you try removing the image Can I get any additional info on how you are running the docker image?
> 
> On Macos 14.3 with apple chip on latest docker, the following works for me run from command line
> 
> ```shell
> docker run -p 3000:3000 -e "SQLPAD_ADMIN=admin@sqlpad.com" -e "SQLPAD_ADMIN_PASSWORD=admin" sqlpad/sqlpad:latest
> ```

I installed the latest version from 7.2

**Comment by Thomas-Rice** [comment]
I'm also experiencing this issue when using version 7.3. 
`node:internal/modules/cjs/loader:1282
  return process.dlopen(module, path.toNamespacedPath(filename));
                 ^
Error: libodbc.so.2: cannot open shared object file: No such file or directory
    at Object.Module._extensions..node (node:internal/modules/cjs/loader:1282:18)
    at Module.load (node:internal/modules/cjs/loader:1076:32)
    at Function.Module._load (node:internal/modules/cjs/loader:911:12)
    at Module.require (node:internal/modules/cjs/loader:1100:19)
    at require (node:internal/modules/cjs/helpers:119:18)
    at Object.<anonymous> (/usr/app/node_modules/odbc/lib/odbc.js:6:20)
    at Module._compile (node:internal/modules/cjs/loader:1198:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1252:10)
    at Module.load (node:internal/modules/cjs/loader:1076:32)
    at Function.Module._load (node:internal/modules/cjs/loader:911:12)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/translators:169:29)
    at ModuleJob.run (node:internal/modules/esm/module_job:193:25)
    at async Promise.all (index 0)
    at async ESMLoader.import (node:internal/modules/esm/loader:530:24)
    at async initDrivers (file:///usr/app/drivers/index.js:46:24)
    at async startServer (file:///usr/app/server.js:172:3) {
  code: 'ERR_DLOPEN_FAILED'`
  
  As a note, rolling back to 7.2 works.

**Comment by rickbergfalk** [comment]
Thanks all for the info. @qqletter you can rollback to 7.2 without clearing or changing anything. It is backwards compatible.

I'm going to have to see if I can reproduce it. It looks like its related to the optional ODBC implementation, and something about it isn't liking the switch to ESM module format.

**Comment by rickbergfalk** [comment]
I've reproduced it! It seems this is a problem for `amd64` image only. I don't have the issue when running `arm64` image.

Still not sure why this is an issue. Will investigate later tonight.

**Comment by rickbergfalk** [comment]
I've pushed version 7.3.1 to docker hub, that should hopefully fix this issue. It addressed my local reproduction case anyways.

Let me know how it goes

**Comment by qqletter** [comment]
> I've pushed version 7.3.1 to docker hub that should hopefully fix this issue. It addressed my local reproduction case anyways.
> 
> Let me know how it goes

I've upgraded to the latest version, it works! Thanks a lot!
