### ISSUE TITLE
Docker latest (updated 3 hours ago as of post) clickhouse error

### ISSUE THREAD

**Issue by Shadow00Caster** [sqlpad/sqlpad#988]
Updated latest earlier today and now I am getting the below error and sqlpad does not start.

Host:
OS Information | linux x86_64 Ubuntu 18.04.5 LTS
Kernel Version | 4.15.0-112-generic
Total CPU | 6
Total memory | 12.6 GB

Engine:
Version | 18.06.3-ce (API: 1.38)
Root directory | /var/lib/docker
Storage Driver | overlay2
Logging Driver | json-file
Volume Plugins | local
Network Plugins | bridge, host, macvlan, null, overlay

```
Error: Cannot find module 'clickhouse'
Require stack:
- /usr/app/drivers/clickhouse/index.js
- /usr/app/drivers/index.js
- /usr/app/lib/validate-connection.js
- /usr/app/lib/config/index.js
- /usr/app/server.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:815:15)
    at Function.Module._load (internal/modules/cjs/loader.js:667:27)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/usr/app/drivers/clickhouse/index.js:1:24)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/usr/app/drivers/clickhouse/index.js',
    '/usr/app/drivers/index.js',
    '/usr/app/lib/validate-connection.js',
    '/usr/app/lib/config/index.js',
    '/usr/app/server.js'
  ]
}
internal/modules/cjs/loader.js:818
   throw err;
   ^
```

**Comment by rickbergfalk** [comment]
Thanks for reporting this! Something weird happened with package-lock.json files. I pushed an update... will confirm and close once docker build finishes.

**Comment by Shadow00Caster** [comment]
@rickbergfalk Thanks!  The push to latest appears to be working now.

**Comment by rickbergfalk** [comment]
`latest` tag is fixed
